/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Skygod;

import net.minestom.server.MinecraftServer;
import net.minestom.server.event.player.PlayerDisconnectEvent;
import net.minestom.server.event.player.PlayerLoginEvent;
import net.minestom.server.event.player.PlayerSpawnEvent;
import net.minestom.server.network.ConnectionManager;
import Skygod.Events.PlayerDisconnect;
import Skygod.Events.PlayerLogin;
import Skygod.Events.PlayerSpawn;
import Skygod.Instances.HubInstance;

public class SkygodServer {
    public static void main(String[] args) {
        // Initialization
        MinecraftServer minecraftServer = MinecraftServer.init();
        
        // Prepare hub instance
        HubInstance.init();
        
        // Register connection event
        ConnectionManager connectionManager = MinecraftServer.getConnectionManager();
        connectionManager.addPlayerInitialization(player -> {
        	// Add event listeners
            player.addEventCallback(PlayerLoginEvent.class, event -> {PlayerLogin.Event(event);});
            player.addEventCallback(PlayerSpawnEvent.class, event -> {PlayerSpawn.Event(event);});
            player.addEventCallback(PlayerDisconnectEvent.class, event -> {PlayerDisconnect.Event(event);});
            
        });

        // Start the server
        minecraftServer.start("localhost", 25565);
    }
}