/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Skygod;

import Skygod.Events.PlayerDisconnect;
import Skygod.Events.PlayerLogin;
import Skygod.Events.PlayerSpawn;
import Skygod.Generators.BlockMappings;
import Skygod.Stages.InstanceList;
import Skygod.Stages.Hub.HubInstance;
import net.minestom.server.MinecraftServer;
import net.minestom.server.event.player.PlayerDisconnectEvent;
import net.minestom.server.event.player.PlayerLoginEvent;
import net.minestom.server.event.player.PlayerSpawnEvent;
import net.minestom.server.network.ConnectionManager;

public class SkygodServer {
    public static void main(String[] args) {
    	
        // Initialization
        MinecraftServer minecraftServer = MinecraftServer.init();
        
        // Register events
        ConnectionManager connectionManager = MinecraftServer.getConnectionManager();
        connectionManager.addPlayerInitialization(player -> {
        	// Add event listeners
            player.addEventCallback(PlayerLoginEvent.class, event -> {PlayerLogin.Event(event);});
            player.addEventCallback(PlayerSpawnEvent.class, event -> {PlayerSpawn.Event(event);});
            player.addEventCallback(PlayerDisconnectEvent.class, event -> {PlayerDisconnect.Event(event);});
            
        });
        
        // Do some pre-loading (not needed, mostly for speed)
        BlockMappings.get();
        HubInstance.get();
        InstanceList.get();
        
        // Testing Area
        // Do testing code here
        
        // Start the server
        minecraftServer.start("localhost", 25565);
    }
}