/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Skygod;

import Skygod.Events.Events;
import net.minestom.server.MinecraftServer;
import net.minestom.server.network.ConnectionManager;

public class SkygodServer {
    public static void main(String[] args) {
    	
        // Initialization
        MinecraftServer minecraftServer = MinecraftServer.init();
        
        // Register events
        ConnectionManager connectionManager = MinecraftServer.getConnectionManager();
        connectionManager.addPlayerInitialization(player -> {Events.registerEvents(player);});
        
        // Do some pre-loading (not needed, mostly for speed)
        
        // Testing Area
        // Do testing code here
        
        // Start the server
        minecraftServer.start("localhost", 25565);
    }
}